apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: 576714096343.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 576714096343.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 96f2599b
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
